### PR TITLE
Small changes / rollbacks on the BreakIterator PR

### PR DESCRIPTION
**Pull request by olbat**
See https://github.com/olbat/icu.cr/pull/8

### CODE REVIEW

**Comment by kostya** [comment]
there is something strange with benchmark
it inifinite slow

**Comment by olbat** [comment]
That's sad :disappointed:

I've created [another benchmark](https://gist.github.com/olbat/cbef9a4a8c1eae99ef2881e3cad28bdf) with more examples, can you run it (with `--release`) on the two versions of the code and post the results ?

**Comment by olbat** [comment]
Here is what I got:
```bash
$ cat stats-olbat.txt                  0
                  user     system      total        real
#0 char       0.260000   0.000000   0.260000 (  0.255680)
#0 word       0.240000   0.000000   0.240000 (  0.246169)
#0 sentence   0.240000   0.000000   0.240000 (  0.240622)
#1 char       4.490000   0.000000   4.490000 (  4.487411)
#1 word       4.500000   0.000000   4.500000 (  4.491598)
#1 sentence   4.490000   0.000000   4.490000 (  4.487444)
#2 char       0.990000   0.000000   0.990000 (  0.981609)
#2 word       0.990000   0.000000   0.990000 (  0.987552)
#2 sentence   0.980000   0.000000   0.980000 (  0.982587)
#3 char       0.720000   0.000000   0.720000 (  0.717322)
#3 word       0.720000   0.000000   0.720000 (  0.722838)
#3 sentence   0.720000   0.000000   0.720000 (  0.717843)
#4 char       0.940000   0.000000   0.940000 (  0.933034)
#4 word       0.940000   0.000000   0.940000 (  0.939075)
#4 sentence   0.940000   0.000000   0.940000 (  0.933845)
#5 char       2.840000   0.010000   2.850000 (  2.844117)
#5 word       2.850000   0.000000   2.850000 (  2.848064)
#5 sentence   2.850000   0.000000   2.850000 (  2.844292)

$ cat stats-kostya.txt 
                  user     system      total        real
#0 char       0.020000   0.000000   0.020000 (  0.025296)
#0 word       0.040000   0.000000   0.040000 (  0.029130)
#0 sentence   0.020000   0.000000   0.020000 (  0.024454)
#1 char       0.060000   0.000000   0.060000 (  0.049740)
#1 word       0.050000   0.010000   0.060000 (  0.055152)
#1 sentence   0.050000   0.000000   0.050000 (  0.050614)
#2 char       0.040000   0.000000   0.040000 (  0.034947)
#2 word       0.040000   0.000000   0.040000 (  0.038611)
#2 sentence   0.040000   0.000000   0.040000 (  0.034285)
#3 char       0.040000   0.000000   0.040000 (  0.031564)
#3 word       0.040000   0.000000   0.040000 (  0.037261)
#3 sentence   0.030000   0.000000   0.030000 (  0.032413)
#4 char       0.040000   0.000000   0.040000 (  0.033402)
#4 word       0.040000   0.000000   0.040000 (  0.038045)
#4 sentence   0.040000   0.000000   0.040000 (  0.033904)
#5 char       0.050000   0.000000   0.050000 (  0.046347)
#5 word       0.050000   0.000000   0.050000 (  0.050526)
#5 sentence   0.050000   0.000000   0.050000 (  0.045432)
```
I'll try to find out what's wrong with my modifications ASAP.

**Comment by kostya** [comment]
this `at(i)` really slow, because it calcualte from begining of string every time.

**Comment by olbat** [comment]
I came with a new implementation, here are the results (_a16_: your implem, _s16_: mine)

```
$ cat t-a16-chars
                  user     system      total        real
#0 char       0.060000   0.000000   0.060000 (  0.056239)
#0 word       0.060000   0.010000   0.070000 (  0.066788)
#0 sentence   0.060000   0.000000   0.060000 (  0.055221)
#1 char       0.120000   0.000000   0.120000 (  0.112415)
#1 word       0.140000   0.000000   0.140000 (  0.124784)
#1 sentence   0.130000   0.000000   0.130000 (  0.113123)
#2 char       0.080000   0.000000   0.080000 (  0.076304)
#2 word       0.090000   0.000000   0.090000 (  0.087064)
#2 sentence   0.090000   0.000000   0.090000 (  0.078236)
#3 char       0.080000   0.000000   0.080000 (  0.071966)
#3 word       0.090000   0.000000   0.090000 (  0.084773)
#3 sentence   0.080000   0.000000   0.080000 (  0.072794)
#4 char       0.080000   0.000000   0.080000 (  0.076134)
#4 word       0.090000   0.000000   0.090000 (  0.086572)
#4 sentence   0.080000   0.000000   0.080000 (  0.076641)
#5 char       0.120000   0.000000   0.120000 (  0.101497)
#5 word       0.120000   0.000000   0.120000 (  0.114038)
#5 sentence   0.110000   0.000000   0.110000 (  0.102648)

$ cat t-a16-each_char
                  user     system      total        real
#0 char       0.060000   0.000000   0.060000 (  0.060168)
#0 word       0.070000   0.000000   0.070000 (  0.069188)
#0 sentence   0.060000   0.000000   0.060000 (  0.058356)
#1 char       0.110000   0.010000   0.120000 (  0.111004)
#1 word       0.130000   0.000000   0.130000 (  0.121025)
#1 sentence   0.110000   0.000000   0.110000 (  0.109311)
#2 char       0.080000   0.000000   0.080000 (  0.074110)
#2 word       0.080000   0.000000   0.080000 (  0.085447)
#2 sentence   0.070000   0.000000   0.070000 (  0.074978)
#3 char       0.070000   0.000000   0.070000 (  0.068254)
#3 word       0.080000   0.000000   0.080000 (  0.079913)
#3 sentence   0.070000   0.000000   0.070000 (  0.070910)
#4 char       0.080000   0.000000   0.080000 (  0.071421)
#4 word       0.090000   0.000000   0.090000 (  0.084535)
#4 sentence   0.070000   0.000000   0.070000 (  0.072350)
#5 char       0.090000   0.000000   0.090000 (  0.089390)
#5 word       0.100000   0.000000   0.100000 (  0.099691)
#5 sentence   0.090000   0.000000   0.090000 (  0.090451)
```

```
$ cat t-s16-v1
                  user     system      total        real
#0 char       0.540000   0.010000   0.550000 (  0.546101)
#0 word       0.570000   0.000000   0.570000 (  0.565373)
#0 sentence   0.550000   0.000000   0.550000 (  0.547736)
#1 char       10.260000   0.000000   10.260000 (  10.259296)
#1 word       10.260000   0.000000   10.260000 (  10.264724)
#1 sentence   10.260000   0.000000   10.260000 (  10.253762)
#2 char       2.240000   0.000000   2.240000 (  2.235242)
#2 word       2.250000   0.000000   2.250000 (  2.250115)
#2 sentence   2.240000   0.000000   2.240000 (  2.235211)
#3 char       1.650000   0.000000   1.650000 (  1.652430)
#3 word       1.660000   0.000000   1.660000 (  1.663655)
#3 sentence   1.660000   0.000000   1.660000 (  1.648683)
#4 char       2.120000   0.000000   2.120000 (  2.128543)
#4 word       2.140000   0.000000   2.140000 (  2.136350)
#4 sentence   2.130000   0.000000   2.130000 (  2.124281)
#5 char       6.470000   0.010000   6.480000 (  6.473237)
#5 word       6.480000   0.000000   6.480000 (  6.476820)
#5 sentence   6.470000   0.000000   6.470000 (  6.465912)
```

```
$ cat t-s16-v2-chars
                  user     system      total        real
#0 char       0.050000   0.010000   0.060000 (  0.056969)
#0 word       0.070000   0.000000   0.070000 (  0.066309)
#0 sentence   0.060000   0.000000   0.060000 (  0.054237)
#1 char       0.130000   0.000000   0.130000 (  0.114816)
#1 word       0.130000   0.000000   0.130000 (  0.127080)
#1 sentence   0.130000   0.000000   0.130000 (  0.114888)
#2 char       0.080000   0.000000   0.080000 (  0.076778)
#2 word       0.090000   0.000000   0.090000 (  0.088842)
#2 sentence   0.090000   0.000000   0.090000 (  0.077036)
#3 char       0.070000   0.010000   0.080000 (  0.073623)
#3 word       0.090000   0.000000   0.090000 (  0.085388)
#3 sentence   0.080000   0.000000   0.080000 (  0.073527)
#4 char       0.080000   0.000000   0.080000 (  0.075482)
#4 word       0.100000   0.000000   0.100000 (  0.086642)
#4 sentence   0.080000   0.000000   0.080000 (  0.077979)
#5 char       0.110000   0.000000   0.110000 (  0.099229)
#5 word       0.110000   0.000000   0.110000 (  0.111765)
#5 sentence   0.110000   0.000000   0.110000 (  0.099669)

$ cat t-s16-v2-each_char
                  user     system      total        real
#0 char       0.050000   0.000000   0.050000 (  0.045818)
#0 word       0.060000   0.000000   0.060000 (  0.057278)
#0 sentence   0.040000   0.000000   0.040000 (  0.044533)
#1 char       0.080000   0.000000   0.080000 (  0.072886)
#1 word       0.080000   0.000000   0.080000 (  0.084229)
#1 sentence   0.080000   0.000000   0.080000 (  0.072592)
#2 char       0.060000   0.000000   0.060000 (  0.055242)
#2 word       0.070000   0.000000   0.070000 (  0.067081)
#2 sentence   0.050000   0.010000   0.060000 (  0.056260)
#3 char       0.060000   0.000000   0.060000 (  0.052301)
#3 word       0.060000   0.000000   0.060000 (  0.062626)
#3 sentence   0.060000   0.000000   0.060000 (  0.052975)
#4 char       0.060000   0.000000   0.060000 (  0.055065)
#4 word       0.060000   0.000000   0.060000 (  0.070417)
#4 sentence   0.060000   0.000000   0.060000 (  0.056168)
#5 char       0.080000   0.000000   0.080000 (  0.067199)
#5 word       0.080000   0.010000   0.090000 (  0.079425)
#5 sentence   0.070000   0.000000   0.070000 (  0.067749)
```

**Comment by olbat** [comment]
> this at(i) really slow, because it calcualte from begining of string every time.
Yup I saw that, that was stupid to implement it this way ... It's fixed now :)

**Comment by kostya** [comment]
also you call `size()` this is also slowdown, because it iterate over chars one more time.

**Comment by olbat** [comment]
Yes but for this one I don't think I can do anything, I need to know how much to allocate before starting to copy the string ...

**Comment by kostya** [comment]
```crystal
chars = str.each_char.map{|x| x.ord.to_u16 }.to_a
Slice(UInt16).new(chars.to_unsafe, chars.size)
```

**Comment by olbat** [comment]
😳 I should have take a look at the code before, ty !

**Comment by olbat** [comment]
Here are the results with this version:
```
                  user     system      total        real
#0 char       0.060000   0.000000   0.060000 (  0.060314)
#0 word       0.070000   0.000000   0.070000 (  0.068843)
#0 sentence   0.060000   0.000000   0.060000 (  0.058103)
#1 char       0.120000   0.010000   0.130000 (  0.116311)
#1 word       0.130000   0.000000   0.130000 (  0.125953)
#1 sentence   0.120000   0.000000   0.120000 (  0.113087)
#2 char       0.080000   0.000000   0.080000 (  0.075282)
#2 word       0.080000   0.000000   0.080000 (  0.085924)
#2 sentence   0.080000   0.000000   0.080000 (  0.075709)
#3 char       0.080000   0.000000   0.080000 (  0.071724)
#3 word       0.090000   0.000000   0.090000 (  0.098662)
#3 sentence   0.080000   0.000000   0.080000 (  0.072939)
#4 char       0.070000   0.010000   0.080000 (  0.073242)
#4 word       0.090000   0.000000   0.090000 (  0.084704)
#4 sentence   0.080000   0.000000   0.080000 (  0.074241)
#5 char       0.090000   0.000000   0.090000 (  0.090843)
#5 word       0.100000   0.000000   0.100000 (  0.100874)
#5 sentence   0.100000   0.000000   0.100000 (  0.090484)
```
It seems to be slower, `#size` probably dont have to iterate over the String in this example.

**Comment by olbat** [comment]
If you're OK with the changes, can you merge this PR so I can merge the one in the other repo ?

**Comment by olbat** [comment]
(I'll be absent for 4-5 days, I'll merge this when I come back)

**Comment by olbat** [comment]
ping @kostya ?

**Pull request closed without merging**
